name: 'Bun Setup, build and test'
description: 'Sets up Bun, installs dependencies, runs tests and builds'

inputs:
  run-playwright:
    description: 'Whether to run Playwright tests'
    default: 'true'
    required: false
  run-coverage:
    description: 'Whether to run coverage'
    default: 'true'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Get Bun version
      id: bun-version
      shell: bash
      run: echo "version=$(bun --version)" >> $GITHUB_OUTPUT

    - name: Cache bun dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-bun-${{ steps.bun-version.outputs.version }}-${{ hashFiles('**/bun.lockb') }}-${{ inputs.run-playwright }}-${{ inputs.run-coverage }}
        restore-keys: |
          ${{ runner.os }}-bun-${{ steps.bun-version.outputs.version }}-${{ hashFiles('**/bun.lockb') }}
          ${{ runner.os }}-bun-${{ steps.bun-version.outputs.version }}-

    - name: Install dependencies
      shell: bash
      run: bun install

    - name: Lint
      shell: bash
      run: bun run lint

    - name: Build
      shell: bash
      run: bun run build

    - name: Run tests
      shell: bash
      run: bun run test

    - name: Run Playwright tests
      if: inputs.run-playwright == 'true'
      shell: bash
      run: bun run test:playwright

    - name: Run coverage
      if: inputs.run-coverage == 'true'
      shell: bash
      run: bun run coverage
