name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Get Bun version
        id: bun-version
        run: echo "version=$(bun --version)" >> $GITHUB_OUTPUT

      - name: Cache bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-bun-${{ steps.bun-version.outputs.version }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ steps.bun-version.outputs.version }}-

      - run: bun install
      - run: bun run lint
      - run: bun run build
      - run: bun run test
      - run: bun run test:playwright
      - run: bun run coverage
