# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: ./.github/actions/bun-setup
